INSERT INTO permissions (name)
VALUES ('ACCOUNT_CREATE')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name)
VALUES ('ACCOUNT_READ')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name)
VALUES ('ACCOUNT_UPDATE')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name)
VALUES ('ACCOUNT_DELETE')
ON CONFLICT (name) DO NOTHING;